# Use rails backblaze to set the backblaze
development:
  account_id: 7eeeecf0aba4
  application_key: 00030ec35b90b187036671d7a3e6c14268f04f36ce
  bucket: crawler-instagram
production:
  account_id: 7eeeecf0aba4
  application_key: 00030ec35b90b187036671d7a3e6c14268f04f36ce
  bucket: crawler-instagram