---
development:
  cloud_name: dcqbean
  api_key: 251127759461936
  api_secret: CEHW5Ugu1dfevM7qxnToJV1Is-o
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dcqbean
  api_key: 251127759461936
  api_secret: CEHW5Ugu1dfevM7qxnToJV1Is-o
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dcqbean
  api_key: 251127759461936
  api_secret: CEHW5Ugu1dfevM7qxnToJV1Is-o
  enhance_image_tag: true
  static_file_support: false
