development:
  stripe_publishable_key: pk_test_jHbD4scNy2WTl4c0rZCHen1g00ZJblHvOu
  stripe_secret_key: sk_test_Nh3Nr9OAhM7cAPUMcM9DSPAV00yOh4VO9y
production:
  stripe_publishable_key: pk_test_jHbD4scNy2WTl4c0rZCHen1g00ZJblHvOu
  stripe_secret_key: sk_test_Nh3Nr9OAhM7cAPUMcM9DSPAV00yOh4VO9y
